### PR TITLE
Use Basho's eleveldb 1.4.1

### PR DESCRIPTION
**Pull request by michaelklishin**
I don't think using a fork is still necessary.

### CODE REVIEW

**Comment by carlhoerberg** [comment]
The problem is this: https://github.com/basho/eleveldb/pull/122
Rebar isn't run properly when compiling so the vsn in app.src isn't replaced, so it won't compile.

**Comment by michaelklishin** [comment]
Alright, we'll investigate if `2.0.0` preview releases work well.

**Comment by michaelklishin** [comment]
Ah, I've noticed that Basho rejected your PR. So we'll have to work around this :(

**Comment by carlhoerberg** [comment]
Yeah, I don't know why all stages in rebar isn't executed when the plugin is compiled :/

**Comment by michaelklishin** [comment]
@carlhoerberg I see

```
sed -e 's|{vsn, *\"[^\"]*\"|{vsn,\"1.4.1-rmq0.0.0-git0e4e4e7\"|' <eleveldb_wrapper-git/src/eleveldb.app.src >build/eleveldb.app.1.4.1-rmq0.0.0-git0e4e4e7
```

with Rebar `2.5` but not `2.1` which I had for years without realising it. Trying to build with Basho's version at `1.4.1` now.

**Comment by michaelklishin** [comment]
@carlhoerberg with Rebar 2.5 I now have

```
cat eleveldb_wrapper-git/ebin/eleveldb.app
{application,eleveldb,
             [{description,[]},
              {vsn,"2.0.1-2-g0e4e4e7"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[{total_leveldb_mem_percent,15},{use_bloomfilter,true}]},
              {modules,[eleveldb,eleveldb_bump]}]}.
```

and the wrapper builds fine. However, there's a newer eleveldb release, I'll test some more and submit another PR.

**Comment by carlhoerberg** [comment]
Nice! Is rebar shipped with umbrella or something?

**Comment by michaelklishin** [comment]
No. You have to install it yourself.

**Pull request closed without merging**
